/**
 * Generated by @openapi-codegen
 *
 * @version 0.1.0
 */
import * as reactQuery from 'react-query'
import { useMantikContext, MantikContext } from './mantikContext'
import type * as Fetcher from './mantikFetcher'
import { mantikFetch } from './mantikFetcher'

export type QueryOperation = {
    path: string
    operationId: never
    variables: unknown
}
