parameters:
    - name: projectId
      in: path
      required: true
      schema:
          type: string
          format: uuid
    - name: codeRepositoryId
      in: path
      required: true
      schema:
          type: string
          format: uuid
get:
    summary: Returns the settings for a specific code repository of a given project
    responses:
        '200':
            description: OK
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            settings:
                                $ref: '../../../../../schemas/CodeRepositorySettings.yaml'
post:
    summary: Updates the settings for a specific code repository of a given project
    requestBody:
        description: Update code repository settings
        required: true
        content:
            application/json:
                schema:
                    $ref: '../../../../../schemas/CodeRepositorySettings.yaml'
    responses:
        '200':
            description: Successfully updated code repository settings
