parameters:
    - name: projectId
      in: path
      required: true
      schema:
          type: string
          format: uuid
    - name: codeRepositoryId
      in: path
      required: true
      schema:
          type: string
          format: uuid
get:
    summary: Returns the settings for a specific code repository of a given project
    responses:
        '200':
            description: OK
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            settings:
                                $ref: '../../../../../schemas/CodeRepositorySettings.yaml'

                    examples:
                        exampleModelRepositories:
                            value:
                                $ref: '../../../../../examples/codeRepositorySettings.json'
post:
    summary: Updates project settings
    requestBody:
        description: Update project settings
        required: true
        content:
            application/json:
                schema:
                    $ref: '../../../../../schemas/CodeRepositorySettings.yaml'
    responses:
        '200':
            description: Successfully updated project settings
