parameters:
    - name: projectId
      in: path
      required: true
      schema:
          type: string
          format: uuid
get:
    summary: Returns the settings for a given project
    responses:
        '200':
            description: OK
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            settings:
                                $ref: '../../../schemas/ProjectSettings.yaml'
post:
    summary: Updates the settings of a given project
    requestBody:
        description: Update project settings
        required: true
        content:
            application/json:
                schema:
                    $ref: '../../../schemas/ProjectSettings.yaml'
    responses:
        '200':
            description: Successfully updated project settings
