type: object
description: Code Repository Settings
properties:
    projectUrl:
        type: string
    environment:
        type: string
    deploymentModes:
        type: array
        items:
            $ref: './DeploymentMode.yaml'
    entryPoints:
        type: array
        items:
            $ref: './EntryPoint.yaml'
    public:
        type: boolean
    owner:
        $ref: './User.yaml'
    userGroups:
        type: array
        items:
            type: object
            properties:
                allowedToEdit:
                    type: boolean
                userGroup:
                    $ref: './UserGroup.yaml'
    users:
        type: array
        items:
            type: object
            properties:
                allowedToEdit:
                    type: boolean
                user:
                    $ref: './User.yaml'
    accessToken:
        type: string
required:
