type: object
description: Project Settings
properties:
    name:
        type: string
    shortDescription:
        type: string
    public:
        type: boolean
    labels:
        type: array
        items:
            $ref: ./Label.yaml
    owner:
        $ref: ./User.yaml
    userGroups:
        type: array
        items:
            type: object
            properties:
                allowedToEdit:
                    type: boolean
                userGroup:
                    $ref: ./UserGroup.yaml
    users:
        type: array
        items:
            type: object
            properties:
                allowedToEdit:
                    type: boolean
                user:
                    $ref: ./User.yaml
required:
