parameters:
    - name: userId
      in: path
      required: true
      schema:
          type: string
          format: uuid
get:
    summary: Returns the settings for a specific user
    responses:
        '200':
            description: OK
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            settings:
                                $ref: '../../../schemas/UserSettings.yaml'
post:
    summary: Updates user settings
    requestBody:
        description: Updated user settings
        required: true
        content:
            application/json:
                schema:
                    $ref: '../../../schemas/UserSettings.yaml'
    responses:
        '200':
            description: Successfully updated settings
