/**
 * Generated by orval v6.9.2 🍺
 * Do not edit manually.
 * Mantik minimal API
 * The API serves the front end with all necessary information on projects, and users.
 * OpenAPI spec version: 0.1.0
 */
import type { ExperimentRepository } from './experimentRepository'
import type { ModelRepository } from './modelRepository'
import type { DataRepository } from './dataRepository'
import type { Connection } from './connection'

/**
 * Necessary information reproduce a run
 */
export interface AddRun {
    experimentRepository?: ExperimentRepository
    modelRepository?: ModelRepository
    dataRepository?: DataRepository
    connection?: Connection
}
