/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Mantik minimal API
 * The API serves the front end with all necessary information on projects, and users.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Represents a connection to a third-party platform, usually either HPC or cloud platform credentials
 */
export interface Connection {
    connectionId: string
    connectionName: string
    connectionProvider: string
    loginName?: string
    password?: string
    token?: string
    authMethod?: string
}
