/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Mantik minimal API
 * The API serves the front end with all necessary information on projects, and users.
 * OpenAPI spec version: 0.1.0
 */
import type { SavedModelRepository } from './savedModelRepository'
import type { Connection } from './connection'
import type { Resources } from './resources'

/**
 * Information on a deployment
 */
export interface DeploymentInformation {
    deploymentId?: string
    savedModelId?: SavedModelRepository
    connection?: Connection
    resources?: Resources
    cronString?: string
}
