/**
 * Generated by orval v6.9.2 🍺
 * Do not edit manually.
 * Mantik minimal API
 * The API serves the front end with all necessary information on projects, and users.
 * OpenAPI spec version: 0.1.0
 */
import type { EntryPointParametersItem } from './entryPointParametersItem'

/**
 * Represents an entry point of a repository
 */
export interface EntryPoint {
    name: string
    parameters?: EntryPointParametersItem[]
}
