/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Mantik minimal API
 * The API serves the front end with all necessary information on projects, and users.
 * OpenAPI spec version: 0.1.0
 */
import type { PaginationResponse } from './paginationResponse'
import type { GetGroups200AllOf } from './getGroups200AllOf'

export type GetGroups200 = PaginationResponse & GetGroups200AllOf
