/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Mantik minimal API
 * The API serves the front end with all necessary information on projects, and users.
 * OpenAPI spec version: 0.1.0
 */
import type { StartIndexParameter } from './startIndexParameter'
import type { PageLengthParameter } from './pageLengthParameter'

export type GetLabelsSearchParams = {
    scope?: string
    searchString?: string
    startindex?: StartIndexParameter
    pagelength?: PageLengthParameter
}
