/**
 * Generated by orval v6.9.2 🍺
 * Do not edit manually.
 * Mantik minimal API
 * The API serves the front end with all necessary information on projects, and users.
 * OpenAPI spec version: 0.1.0
 */
import type { PaginationResponse } from './paginationResponse'
import type { GetLabelsUserIdSearch200AllOf } from './getLabelsUserIdSearch200AllOf'

export type GetLabelsUserIdSearch200 = PaginationResponse &
    GetLabelsUserIdSearch200AllOf
