/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Mantik minimal API
 * The API serves the front end with all necessary information on projects, and users.
 * OpenAPI spec version: 0.1.0
 */
import type { PaginationResponse } from './paginationResponse'
import type { GetProjectsProjectIdDeployments200AllOf } from './getProjectsProjectIdDeployments200AllOf'

export type GetProjectsProjectIdDeployments200 = PaginationResponse &
    GetProjectsProjectIdDeployments200AllOf
