/**
 * Generated by orval v6.9.2 🍺
 * Do not edit manually.
 * Mantik minimal API
 * The API serves the front end with all necessary information on projects, and users.
 * OpenAPI spec version: 0.1.0
 */
import type { PaginationResponse } from './paginationResponse'
import type { GetProjectsProjectIdExperimentsUsage200AllOf } from './getProjectsProjectIdExperimentsUsage200AllOf'

export type GetProjectsProjectIdExperimentsUsage200 = PaginationResponse &
    GetProjectsProjectIdExperimentsUsage200AllOf
