/**
 * Generated by orval v6.9.2 🍺
 * Do not edit manually.
 * Mantik minimal API
 * The API serves the front end with all necessary information on projects, and users.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Represents a label or a (MLFlow-)Tag depending on the presence of the value parameter
 */
export interface Label {
    scope: string
    name: string
    value?: string
}
