/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Mantik minimal API
 * The API serves the front end with all necessary information on projects, and users.
 * OpenAPI spec version: 0.1.0
 */
import type { User } from './user'
import type { UserGroup } from './userGroup'
import type { CodeRepository } from './codeRepository'
import type { ExperimentRepository } from './experimentRepository'
import type { DataRepository } from './dataRepository'

/**
 * A project is a collection of code, experiments, data and models with permission management (owner, members, groups)
 */
export interface Project {
    projectId: number
    owner: User
    members?: User[]
    groups?: UserGroup[]
    codeRepositories?: CodeRepository[]
    experimentRepositories?: ExperimentRepository[]
    dataRepositories?: DataRepository[]
}
