/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Mantik minimal API
 * The API serves the front end with all necessary information on projects, and users.
 * OpenAPI spec version: 0.1.0
 */
import type { Label } from './label'
import type { User } from './user'
import type { ProjectSettingsUserGroupsItem } from './projectSettingsUserGroupsItem'
import type { ProjectSettingsUsersItem } from './projectSettingsUsersItem'

/**
 * Project Settings
 */
export interface ProjectSettings {
    name?: string
    shortDescription?: string
    public?: boolean
    labels?: Label[]
    owner?: User
    userGroups?: ProjectSettingsUserGroupsItem[]
    users?: ProjectSettingsUsersItem[]
}
