/**
 * Generated by orval v6.9.2 🍺
 * Do not edit manually.
 * Mantik minimal API
 * The API serves the front end with all necessary information on projects, and users.
 * OpenAPI spec version: 0.1.0
 */
import type { ExperimentRepository } from './experimentRepository'
import type { ModelRepository } from './modelRepository'
import type { SavedModelRepository } from './savedModelRepository'
import type { DataRepository } from './dataRepository'
import type { Connection } from './connection'
import type { RunStatus } from './runStatus'

/**
 * Represents a quadruple of experiment, code, data and hardware-configuration
 */
export interface Run {
    run_id?: string
    experimentRepository?: ExperimentRepository
    modelRepository?: ModelRepository
    savedModel?: SavedModelRepository
    dataRepository?: DataRepository
    connections?: Connection
    experiment_id?: string
    user_id?: string
    status?: RunStatus
    start_time?: number
    end_time?: number
    artifact_uri?: string
    lifecycle_stage?: string
}
