/**
 * Generated by orval v6.9.2 🍺
 * Do not edit manually.
 * Mantik minimal API
 * The API serves the front end with all necessary information on projects, and users.
 * OpenAPI spec version: 0.1.0
 */

export type RunStatus = typeof RunStatus[keyof typeof RunStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RunStatus = {
    RUNNING: 'RUNNING',
    SCHEDULED: 'SCHEDULED',
    FINISHED: 'FINISHED',
    FAILED: 'FAILED',
    KILLED: 'KILLED',
} as const
