/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Mantik minimal API
 * The API serves the front end with all necessary information on projects, and users.
 * OpenAPI spec version: 0.1.0
 */
import type { DataRepository } from './dataRepository'
import type { RunsByDataRepositoryUsageItem } from './runsByDataRepositoryUsageItem'

/**
 * Runs grouped by the data used
 */
export interface RunsByDataRepository {
    dataRepository?: DataRepository
    usage?: RunsByDataRepositoryUsageItem[]
}
