/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Mantik minimal API
 * The API serves the front end with all necessary information on projects, and users.
 * OpenAPI spec version: 0.1.0
 */
import type { User } from './user'
import type { PaymentInfo } from './paymentInfo'
import type { Connection } from './connection'

/**
 * User settings
 */
export interface UserSettings {
    user: User
    password: string
    token?: string
    paymentInfo?: PaymentInfo
    connections?: Connection[]
}
