name: actions

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    test_e2e:
        if: ${{ false }} # disable for now
        name: Test Cypress e2e
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
            - run: npm install
            - run: npm run test:e2e:headless
            - uses: actions/upload-artifact@v3
              if: failure()
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots
            - uses: actions/upload-artifact@v3
              if: failure()
              with:
                  name: cypress-videos
                  path: cypress/videos
